#
# Example: Legacy Default Admin Role
# Tip: For 6.0+ clusters, please use 'editor' for configuring Teleport
#
kind: role
metadata:
  name: admin
spec:
  allow:
    kubernetes_groups:
    - '{{internal.kubernetes_groups}}'
    windows_desktop_logins:
    - '{{internal.windows_logins}}'
    logins:
    - '{{internal.logins}}'
    - root
    node_labels:
      '*': '*'
    rules:
    - resources:
      - '*'
      verbs:
      - '*'
  deny:
    logins: null
  options:
    cert_format: standard
    enhanced_recording:
    - command
    - network
    forward_agent: true
    max_session_ttl: 30h0m0s
    port_forwarding: true
version: v3
